use_frameworks!

target 'TabDrawer_Example', :exclusive => true do
  pod 'TabDrawer', :path => '../'
  pod 'FontAwesome.swift'
end

target 'TabDrawer_Tests', :exclusive => true do
  pod 'TabDrawer', :path => '../'
  pod 'FontAwesome.swift'
end
